# Source: https://github.com/nestjs/nest/blob/master/sample/05-sql-typeorm/docker-compose.yml

version: "3"

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "33060:3306"
  db-test:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "33070:3306"
